
spring:
    jackson:
        serialization:
            fail-on-empty-beans: false # Hibernate5JakartaModule 대체
    datasource:
        url: jdbc:mysql://localhost:3306/jpashop?userSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        username: admin
        password: admin
        dbcp2:
          driver-class-name: com.mysql.cj.jdbc.Driver
    devtools:
        livereload.enabled: true
    jpa:
        show_sql: true
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                format_sql: true
                default_batch_fetch_size: 100 # ToMany 관계 페이징 + 성능최적화 ( where in 으로 조건 쿼리)


logging.level:
    org.hibernate:
        SQL: debug
        type: trace
#logging.level:
#        org.hibernate.SQL: debug
#        org.hibernate.type.descriptor.sql: trace
#    org.springframework: debug
#    org.springframework.web: debug
server:
    port: 8888