
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/jpashop?userSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        username: admin
        password: admin
        dbcp2:
          driver-class-name: com.mysql.cj.jdbc.Driver
    devtools:
        livereload.enabled: true
    jpa:
        show_sql: true
        hibernate:
            ddl-auto: create
        properties:
            format_sql: true
#        default_batch_fetch_size: 1000 #??? ??

logging.level:
        org.hibernate.SQL: debug
        org.hibernate.type: trace
#    org.springframework: debug
#    org.springframework.web: debug
server:
    port: 8888